version: '3.9'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    links:
      - monguse
    volumes:
      - .:/home/app
  monguse:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: r0O7

    volumes: 
      - mongo-data:/data/db
volumes:
  mongo-data: